regression tag

diff --git a/.github/workflows/regression.yml b/.github/workflows/regression.yml
--- a/.github/workflows/regression.yml
+++ b/.github/workflows/regression.yml
@@ -23,7 +23,7 @@ jobs:
         run: npx playwright install --with-deps
 
       - name: Run Cucumber Smoke Suite
-        run: npm run smoke || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        run: npm run regression || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
       - name: Generate Cucumber HTML Report
         run: npm run report
